### ISSUE TITLE
Rule no-undef should exclude from TypeScript

### ISSUE THREAD

**Issue by progamesigner** [oursky/eslint-oursky#46]
As type-checking is done by TypeScript itself, eslint shouldn't have `no-undef` rule for typescript files.

This will be an error as `JSX` is a global.
```ts
function SomeComp(): JSX.Element {
  // ...
}
```

Official ref: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

**Comment by louischan-oursky** [comment]
Released https://www.npmjs.com/package/@oursky/eslint-plugin/v/13.1.0 to fix this.
