### ISSUE TITLE
[Poll] Ban the use of z-index

### ISSUE THREAD

**Issue by louischan-oursky** [oursky/eslint-oursky#47]
Feel free to let your comments below

**Comment by Amdadullah-Raihan** [comment]
Hello Sir, 

I want to contribute.

**Comment by kiootic** [comment]
I don't think it is needed. There are 2 main reasons to use z-index:
- Manage the draw order of overlapping sibling elements: we have [`isolation`](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation) to help localize the z-index.
- Floating elements (e.g. popups, tooltip): should lift to near-root elements (e.g. body) anyways.

**Comment by Amdadullah-Raihan** [comment]
Sir, 

How do I find the issues that are open to contribute?
